#!/bin/sh

. /etc/profile

case "$1" in
start)
	start-stop-daemon -m -p /var/run/camera.pid -b -a /usr/bin/mplayer -S -- tv://
	;;
stop)
	start-stop-daemon -p /var/run/camera.pid -K
	;;
*)
	echo "Usage: /etc/init.d/camera {start|stop}" >&2
	exit 1
	;;
esac

