#!/bin/sh

. /etc/profile

case "$1" in
start)
	start-stop-daemon -m -p /var/run/qt4-guf-slideshow.pid -b -a /usr/bin/qt4-guf-slideshow -S -- -qws
	;;
stop)
	start-stop-daemon -p /var/run/qt4-guf-slideshow.pid -K
	;;
*)
	echo "Usage: /etc/init.d/qt4-guf-slideshow {start|stop}" >&2
	exit 1
	;;
esac

