######################################################################
# Automatically generated by qmake (2.01a) Mi. Mrz 24 13:14:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainview.h qgufslider.h qdigit.h qslideshow.h \
    platform.h
SOURCES += main.cpp mainview.cpp qgufslider.cpp qdigit.cpp qslideshow.cpp
