#ifndef CAPACITIVE_KEYBOARD_H
#define CAPACITIVE_KEYBOARD_H

/* Registers */
#define HOSTREG_CHIPID			0x00
#define HOSTREG_VERSION			0x01
#define HOSTREG_KEY_STATUS_1		0x02
#define HOSTREG_KEY_STATUS_2		0x03
#define HOSTREG_GPIO_GPO_DRIVE_1	0x04
#define HOSTREG_SUB_REVISION		0x05

#define FIRST_STATUS_BYTE		HOSTREG_KEY_STATUS_1
#define NUM_STATUS_BYTES		2

/* Change Port */
#define PORT_CHANGE PORTD
#define DDR_CHANGE  DDRD
#define CHANGE (1<<5)

#endif /* CAPACITIVE_KEYBOARD_H */
