####################################
# Automatically generated by qmake #
####################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainview.h qslideshow.h images.h
SOURCES += main.cpp mainview.cpp qslideshow.cpp images.cpp
FORMS += mainview.ui